/**
 * Supabase 연결 전 개발용 목 데이터
 */

import type { OrderStatus, ShippingMethod, HighlightType, OrderSource } from '@/types/enums';

const today = new Date();
const formatDate = (d: Date) => d.toISOString().split('T')[0];
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d;
};
const daysLater = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d;
};

export const MOCK_ORDERS = [
  {
    id: '1',
    order_number: 'ORD-2026-001',
    order_source: 'external' as OrderSource,
    status: 'collected' as OrderStatus,
    shipping_method: 'parcel' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(3)),
    collected_at: daysAgo(1).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(3)),
    recipient_name: '김민수',
    recipient_phone: '010-1234-5678',
    recipient_address: '서울시 강남구 역삼동 123-45 현대아파트 101동 202호',
    recipient_zipcode: '06241',
    delivery_message: '부재시 경비실에 맡겨주세요',
    order_amount: 45000,
    total_product_count: 1,
    total_item_quantity: 2,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: null,
    print_ready_at: null,
    print_completed_at: null,
    binding_completed_at: null,
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(1).toISOString(),
    updated_at: daysAgo(1).toISOString(),
    order_items: [
      {
        id: 'item-1',
        order_id: '1',
        product_id: 'prod-1',
        product_name: '프리미엄 포토북 A4',
        product_code: 'PB-A4-001',
        quantity: 2,
        item_price: 22500,
        box_type_id: 'box-1',
        box_type_name: '일반박스',
        sticker_type1_id: 'st-1',
        sticker_type1_name: '로고스티커',
        sticker_type1_quantity: 2,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '사랑하는 엄마에게 생일 축하합니다!',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(1).toISOString(),
        updated_at: daysAgo(1).toISOString(),
      },
    ],
    order_highlights: [],
    admin_memos: [],
    order_shipping_addresses: [],
    highlights: [] as HighlightType[],
    latest_memo: null,
  },
  {
    id: '2',
    order_number: 'ORD-2026-002',
    order_source: 'external' as OrderSource,
    status: 'collected' as OrderStatus,
    shipping_method: 'same_day' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(1)),
    collected_at: daysAgo(0).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(2)),
    recipient_name: '이영희',
    recipient_phone: '010-9876-5432',
    recipient_address: '서울시 송파구 잠실동 234-56',
    recipient_zipcode: '05510',
    delivery_message: '',
    order_amount: 68000,
    total_product_count: 2,
    total_item_quantity: 3,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: null,
    print_ready_at: null,
    print_completed_at: null,
    binding_completed_at: null,
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(0).toISOString(),
    updated_at: daysAgo(0).toISOString(),
    order_items: [
      {
        id: 'item-2a',
        order_id: '2',
        product_id: 'prod-1',
        product_name: '프리미엄 포토북 A4',
        product_code: 'PB-A4-001',
        quantity: 1,
        item_price: 22500,
        box_type_id: 'box-1',
        box_type_name: '일반박스',
        sticker_type1_id: 'st-1',
        sticker_type1_name: '로고스티커',
        sticker_type1_quantity: 1,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '우리 가족 여행 기념',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(0).toISOString(),
        updated_at: daysAgo(0).toISOString(),
      },
      {
        id: 'item-2b',
        order_id: '2',
        product_id: 'prod-2',
        product_name: '미니 포토카드 세트',
        product_code: 'PC-MINI-002',
        quantity: 2,
        item_price: 22750,
        box_type_id: 'box-2',
        box_type_name: '선물박스',
        sticker_type1_id: 'st-2',
        sticker_type1_name: '하트스티커',
        sticker_type1_quantity: 1,
        sticker_type2_id: 'st-3',
        sticker_type2_name: '별스티커',
        sticker_type2_quantity: 1,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '사랑해요 ♥',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 1,
        created_at: daysAgo(0).toISOString(),
        updated_at: daysAgo(0).toISOString(),
      },
    ],
    order_highlights: [{ highlight_type: 'multi_product' }, { highlight_type: 'schedule_changed' }],
    admin_memos: [],
    order_shipping_addresses: [],
    highlights: ['multi_product', 'schedule_changed'] as HighlightType[],
    latest_memo: null,
  },
  {
    id: '3',
    order_number: 'ORD-2026-003',
    order_source: 'admin' as OrderSource,
    status: 'collected' as OrderStatus,
    shipping_method: 'quick' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(0)),
    collected_at: daysAgo(2).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(0)),
    recipient_name: '박지원',
    recipient_phone: '010-5555-1234',
    recipient_address: '서울시 마포구 합정동 456-78',
    recipient_zipcode: '04091',
    delivery_message: '오후 2시 이전 배송 부탁드립니다',
    order_amount: 33000,
    total_product_count: 1,
    total_item_quantity: 1,
    is_incident: true,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: null,
    print_ready_at: null,
    print_completed_at: null,
    binding_completed_at: null,
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: 'admin-user',
    updated_by: null,
    created_at: daysAgo(2).toISOString(),
    updated_at: daysAgo(2).toISOString(),
    order_items: [
      {
        id: 'item-3',
        order_id: '3',
        product_id: 'prod-3',
        product_name: '캘린더 2026',
        product_code: 'CAL-2026-001',
        quantity: 1,
        item_price: 33000,
        box_type_id: 'box-1',
        box_type_name: '일반박스',
        sticker_type1_id: 'st-1',
        sticker_type1_name: '로고스티커',
        sticker_type1_quantity: 1,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(2).toISOString(),
        updated_at: daysAgo(2).toISOString(),
      },
    ],
    order_highlights: [{ highlight_type: 'incident' }, { highlight_type: 'admin_memo' }],
    admin_memos: [
      {
        id: 'memo-1',
        order_id: '3',
        memo_text: '사고건: 기존 배송 파손으로 재제작',
        created_by: 'admin-user',
        created_at: daysAgo(2).toISOString(),
        updated_at: daysAgo(2).toISOString(),
      },
    ],
    order_shipping_addresses: [],
    highlights: ['incident', 'admin_memo'] as HighlightType[],
    latest_memo: '사고건: 기존 배송 파손으로 재제작',
  },
  {
    id: '4',
    order_number: 'ORD-2026-004',
    order_source: 'external' as OrderSource,
    status: 'draft_completed' as OrderStatus,
    shipping_method: 'parcel' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(5)),
    collected_at: daysAgo(3).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(5)),
    recipient_name: '최서연',
    recipient_phone: '010-7777-8888',
    recipient_address: '경기도 성남시 분당구 서현동 111-22',
    recipient_zipcode: '13591',
    delivery_message: '',
    order_amount: 55000,
    total_product_count: 1,
    total_item_quantity: 1,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: daysAgo(2).toISOString(),
    print_ready_at: null,
    print_completed_at: null,
    binding_completed_at: null,
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(3).toISOString(),
    updated_at: daysAgo(2).toISOString(),
    order_items: [
      {
        id: 'item-4',
        order_id: '4',
        product_id: 'prod-1',
        product_name: '프리미엄 포토북 A4',
        product_code: 'PB-A4-001',
        quantity: 1,
        item_price: 55000,
        box_type_id: 'box-2',
        box_type_name: '선물박스',
        sticker_type1_id: 'st-2',
        sticker_type1_name: '하트스티커',
        sticker_type1_quantity: 1,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '결혼 1주년 기념',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(3).toISOString(),
        updated_at: daysAgo(2).toISOString(),
      },
    ],
    order_highlights: [],
    admin_memos: [],
    order_shipping_addresses: [],
    highlights: [] as HighlightType[],
    latest_memo: null,
  },
  {
    id: '5',
    order_number: 'ORD-2026-005',
    order_source: 'external' as OrderSource,
    status: 'print_ready' as OrderStatus,
    shipping_method: 'parcel' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(4)),
    collected_at: daysAgo(5).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(4)),
    recipient_name: '정하윤',
    recipient_phone: '010-3333-4444',
    recipient_address: '부산시 해운대구 우동 567-89',
    recipient_zipcode: '48060',
    delivery_message: '택배함에 넣어주세요',
    order_amount: 42000,
    total_product_count: 1,
    total_item_quantity: 2,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: daysAgo(4).toISOString(),
    print_ready_at: daysAgo(3).toISOString(),
    print_completed_at: null,
    binding_completed_at: null,
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(5).toISOString(),
    updated_at: daysAgo(3).toISOString(),
    order_items: [
      {
        id: 'item-5',
        order_id: '5',
        product_id: 'prod-2',
        product_name: '미니 포토카드 세트',
        product_code: 'PC-MINI-002',
        quantity: 2,
        item_price: 21000,
        box_type_id: 'box-1',
        box_type_name: '일반박스',
        sticker_type1_id: 'st-3',
        sticker_type1_name: '별스티커',
        sticker_type1_quantity: 2,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '졸업 축하해!',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(5).toISOString(),
        updated_at: daysAgo(3).toISOString(),
      },
    ],
    order_highlights: [],
    admin_memos: [],
    order_shipping_addresses: [],
    highlights: [] as HighlightType[],
    latest_memo: null,
  },
  {
    id: '6',
    order_number: 'ORD-2026-006',
    order_source: 'external' as OrderSource,
    status: 'print_completed' as OrderStatus,
    shipping_method: 'terminal' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(2)),
    collected_at: daysAgo(7).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(2)),
    recipient_name: '한소율',
    recipient_phone: '010-6666-7777',
    recipient_address: '대전시 유성구 봉명동 345-67',
    recipient_zipcode: '34186',
    delivery_message: '',
    order_amount: 28000,
    total_product_count: 1,
    total_item_quantity: 1,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: daysAgo(6).toISOString(),
    print_ready_at: daysAgo(5).toISOString(),
    print_completed_at: daysAgo(3).toISOString(),
    binding_completed_at: null,
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(7).toISOString(),
    updated_at: daysAgo(3).toISOString(),
    order_items: [
      {
        id: 'item-6',
        order_id: '6',
        product_id: 'prod-3',
        product_name: '캘린더 2026',
        product_code: 'CAL-2026-001',
        quantity: 1,
        item_price: 28000,
        box_type_id: 'box-1',
        box_type_name: '일반박스',
        sticker_type1_id: 'st-1',
        sticker_type1_name: '로고스티커',
        sticker_type1_quantity: 1,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '2026년도 달력 제작',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(7).toISOString(),
        updated_at: daysAgo(3).toISOString(),
      },
    ],
    order_highlights: [],
    admin_memos: [],
    order_shipping_addresses: [],
    highlights: [] as HighlightType[],
    latest_memo: null,
  },
  {
    id: '7',
    order_number: 'ORD-2026-007',
    order_source: 'external' as OrderSource,
    status: 'binding_completed' as OrderStatus,
    shipping_method: 'parcel' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(1)),
    collected_at: daysAgo(10).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(1)),
    recipient_name: '오지현',
    recipient_phone: '010-2222-3333',
    recipient_address: '인천시 남동구 구월동 789-01',
    recipient_zipcode: '21556',
    delivery_message: '문 앞에 놓아주세요',
    order_amount: 39000,
    total_product_count: 1,
    total_item_quantity: 1,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: daysAgo(9).toISOString(),
    print_ready_at: daysAgo(7).toISOString(),
    print_completed_at: daysAgo(5).toISOString(),
    binding_completed_at: daysAgo(2).toISOString(),
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(10).toISOString(),
    updated_at: daysAgo(2).toISOString(),
    order_items: [
      {
        id: 'item-7',
        order_id: '7',
        product_id: 'prod-1',
        product_name: '프리미엄 포토북 A4',
        product_code: 'PB-A4-001',
        quantity: 1,
        item_price: 39000,
        box_type_id: 'box-2',
        box_type_name: '선물박스',
        sticker_type1_id: 'st-2',
        sticker_type1_name: '하트스티커',
        sticker_type1_quantity: 1,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '영원히 함께해요',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(10).toISOString(),
        updated_at: daysAgo(2).toISOString(),
      },
    ],
    order_highlights: [{ highlight_type: 'split_shipping' }],
    admin_memos: [],
    order_shipping_addresses: [
      {
        id: 'addr-1',
        order_id: '7',
        recipient_name: '오지현(직장)',
        recipient_phone: '010-2222-3334',
        recipient_address: '서울시 종로구 광화문 100',
        recipient_zipcode: '03154',
        delivery_message: '',
        quantity: 1,
        shipping_method: 'parcel' as ShippingMethod,
        tracking_number: null,
        is_primary: false,
        sort_order: 1,
        created_at: daysAgo(5).toISOString(),
        updated_at: daysAgo(5).toISOString(),
      },
    ],
    highlights: ['split_shipping'] as HighlightType[],
    latest_memo: null,
  },
  {
    id: '8',
    order_number: 'ORD-2026-008',
    order_source: 'external' as OrderSource,
    status: 'shipping_completed' as OrderStatus,
    shipping_method: 'parcel' as ShippingMethod,
    desired_shipping_date: formatDate(daysAgo(1)),
    collected_at: daysAgo(14).toISOString(),
    original_desired_shipping_date: formatDate(daysAgo(1)),
    recipient_name: '강도윤',
    recipient_phone: '010-8888-9999',
    recipient_address: '광주시 서구 치평동 234-56',
    recipient_zipcode: '61945',
    delivery_message: '',
    order_amount: 52000,
    total_product_count: 1,
    total_item_quantity: 2,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: daysAgo(13).toISOString(),
    print_ready_at: daysAgo(11).toISOString(),
    print_completed_at: daysAgo(7).toISOString(),
    binding_completed_at: daysAgo(4).toISOString(),
    shipping_completed_at: daysAgo(1).toISOString(),
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(14).toISOString(),
    updated_at: daysAgo(1).toISOString(),
    order_items: [
      {
        id: 'item-8',
        order_id: '8',
        product_id: 'prod-1',
        product_name: '프리미엄 포토북 A4',
        product_code: 'PB-A4-001',
        quantity: 2,
        item_price: 26000,
        box_type_id: 'box-2',
        box_type_name: '선물박스',
        sticker_type1_id: 'st-1',
        sticker_type1_name: '로고스티커',
        sticker_type1_quantity: 2,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '감사합니다',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(14).toISOString(),
        updated_at: daysAgo(1).toISOString(),
      },
    ],
    order_highlights: [],
    admin_memos: [],
    order_shipping_addresses: [],
    highlights: [] as HighlightType[],
    latest_memo: null,
  },
  {
    id: '9',
    order_number: 'ORD-2026-009',
    order_source: 'external' as OrderSource,
    status: 'validation_failed' as OrderStatus,
    shipping_method: 'parcel' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(6)),
    collected_at: daysAgo(1).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(6)),
    recipient_name: '윤서아',
    recipient_phone: '010-1111-2222',
    recipient_address: '대구시 중구 동성로 456',
    recipient_zipcode: '41911',
    delivery_message: '',
    order_amount: 15000,
    total_product_count: 1,
    total_item_quantity: 3,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: '스티커 타입이 2개 이상이며 수량 합계(4)가 주문수량(3)과 불일치',
    validation_failed_at: daysAgo(1).toISOString(),
    draft_completed_at: null,
    print_ready_at: null,
    print_completed_at: null,
    binding_completed_at: null,
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(1).toISOString(),
    updated_at: daysAgo(1).toISOString(),
    order_items: [
      {
        id: 'item-9',
        order_id: '9',
        product_id: 'prod-2',
        product_name: '미니 포토카드 세트',
        product_code: 'PC-MINI-002',
        quantity: 3,
        item_price: 5000,
        box_type_id: 'box-1',
        box_type_name: '일반박스',
        sticker_type1_id: 'st-1',
        sticker_type1_name: '로고스티커',
        sticker_type1_quantity: 2,
        sticker_type2_id: 'st-2',
        sticker_type2_name: '하트스티커',
        sticker_type2_quantity: 2,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '고마워',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(1).toISOString(),
        updated_at: daysAgo(1).toISOString(),
      },
    ],
    order_highlights: [{ highlight_type: 'check_required' }],
    admin_memos: [],
    order_shipping_addresses: [],
    highlights: ['check_required'] as HighlightType[],
    latest_memo: null,
  },
  {
    id: '10',
    order_number: 'ORD-2026-010',
    order_source: 'external' as OrderSource,
    status: 'collected' as OrderStatus,
    shipping_method: 'parcel' as ShippingMethod,
    desired_shipping_date: formatDate(daysLater(7)),
    collected_at: daysAgo(0).toISOString(),
    original_desired_shipping_date: formatDate(daysLater(7)),
    recipient_name: '장현우',
    recipient_phone: '010-4444-5555',
    recipient_address: '울산시 남구 삼산동 678-90',
    recipient_zipcode: '44717',
    delivery_message: '토요일 오전 배송 부탁',
    order_amount: 0,
    total_product_count: 1,
    total_item_quantity: 1,
    is_incident: false,
    is_deleted: false,
    validation_failed_reason: null,
    validation_failed_at: null,
    draft_completed_at: null,
    print_ready_at: null,
    print_completed_at: null,
    binding_completed_at: null,
    shipping_completed_at: null,
    confirmed_at: null,
    confirmed_by: null,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(0).toISOString(),
    updated_at: daysAgo(0).toISOString(),
    order_items: [
      {
        id: 'item-10',
        order_id: '10',
        product_id: 'prod-1',
        product_name: '프리미엄 포토북 A4',
        product_code: 'PB-A4-001',
        quantity: 1,
        item_price: 0,
        box_type_id: 'box-1',
        box_type_name: '일반박스',
        sticker_type1_id: 'st-3',
        sticker_type1_name: '별스티커',
        sticker_type1_quantity: 1,
        sticker_type2_id: null,
        sticker_type2_name: null,
        sticker_type2_quantity: 0,
        sticker_type3_id: null,
        sticker_type3_name: null,
        sticker_type3_quantity: 0,
        input_message: '첫 번째 생일 축하해',
        sticker_preview_url: null,
        sticker_preview_uploaded_at: null,
        sort_order: 0,
        created_at: daysAgo(0).toISOString(),
        updated_at: daysAgo(0).toISOString(),
      },
    ],
    order_highlights: [{ highlight_type: 'check_required' }],
    admin_memos: [],
    order_shipping_addresses: [],
    highlights: ['check_required'] as HighlightType[],
    latest_memo: null,
  },
];

export const MOCK_DASHBOARD_SUMMARY = {
  order_status: {
    total: MOCK_ORDERS.length,
    collected: MOCK_ORDERS.filter((o) => o.status === 'collected').length,
    cancelled: 0,
    validation_failed: MOCK_ORDERS.filter((o) => o.status === 'validation_failed').length,
    system_error: 0,
  },
  work_status: {
    draft_completed: MOCK_ORDERS.filter((o) => o.status === 'draft_completed').length,
    print_ready: MOCK_ORDERS.filter((o) => o.status === 'print_ready').length,
    print_completed: MOCK_ORDERS.filter((o) => o.status === 'print_completed').length,
    binding_completed: MOCK_ORDERS.filter((o) => o.status === 'binding_completed').length,
    shipping_completed: MOCK_ORDERS.filter((o) => o.status === 'shipping_completed').length,
  },
};

export const MOCK_SHIPPING_CALENDAR = [
  {
    month: `${today.getFullYear()}-${String(today.getMonth()).padStart(2, '0')}`,
    total_count: 3,
    label: '',
    is_current: false,
  },
  {
    month: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}`,
    total_count: 8,
    label: '',
    is_current: true,
  },
  {
    month: `${today.getFullYear()}-${String(today.getMonth() + 2).padStart(2, '0')}`,
    total_count: 2,
    label: '',
    is_current: false,
  },
];

export const MOCK_PRODUCTS = [
  { id: 'prod-1', product_code: 'PB-A4-001', product_name: '프리미엄 포토북 A4', price: 45000, is_sticker_product: false, is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
  { id: 'prod-2', product_code: 'PC-MINI-002', product_name: '미니 포토카드 세트', price: 22000, is_sticker_product: false, is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
  { id: 'prod-3', product_code: 'CAL-2026-001', product_name: '캘린더 2026', price: 33000, is_sticker_product: false, is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
  { id: 'prod-4', product_code: 'STK-LOGO-001', product_name: '로고스티커 단품', price: 3000, is_sticker_product: true, is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
];

export const MOCK_STICKER_TYPES = [
  { id: 'st-1', sticker_code: 'ST-LOGO', sticker_name: '로고스티커', is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
  { id: 'st-2', sticker_code: 'ST-HEART', sticker_name: '하트스티커', is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
  { id: 'st-3', sticker_code: 'ST-STAR', sticker_name: '별스티커', is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
];

export const MOCK_BOX_TYPES = [
  { id: 'box-1', box_code: 'BOX-STD', box_name: '일반박스', is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
  { id: 'box-2', box_code: 'BOX-GIFT', box_name: '선물박스', is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
  { id: 'box-3', box_code: 'BOX-PREM', box_name: '프리미엄박스', is_active: true, created_at: daysAgo(30).toISOString(), updated_at: daysAgo(30).toISOString() },
];

export const MOCK_ORDER_HISTORY = [
  { id: 'h-1', order_id: '1', action: 'order_created', field_name: null, old_value: null, new_value: null, description: '주문 수집 완료', performed_by: null, performed_at: daysAgo(1).toISOString() },
];
